### ISSUE TITLE
Convert code to html

### ISSUE THREAD

**Issue by imabot2** [boomanaiden154/quillgethtml#3] opened 2020-02-29 12:11 UTC
On the example provided with the sources, I created a code area in the editor and put `</div>` in the area, here is the result: https://ibb.co/CPbhwBS

I think something is buggy.

**Comment by boomanaiden154** [comment] 2020-03-17 01:25
Sorry for the late response. It is just that when it takes the text from Quill and formats it, it doesn't add any escape characters and this the code within the code blocks gets rendered by the browser which shouldn't be the intended behavior. I should be able to open a PR fixing this issue fairly soon(within a day or two)

**Comment by boomanaiden154** [comment] 2020-03-23 02:33
This should be fixed as of release [0.0.6](https://github.com/boomanaiden154/quillgethtml/releases/tag/v0.0.6), and as of commit b6f093c0176c90374a82a2729fe1a3a30b22bd73. Sorry for taking so long.

**Closed by boomanaiden154** 2020-03-23 02:33 UTC
